### ISSUE TITLE
s3handler.js parsing body isn't working anymore

### ISSUE THREAD

**Issue by quisse** [FineUploader/server-examples#42]
I am using a multipart form parser to get my policy because bodyparser isn't working anymore.

**Comment by dbeg** [comment]
The Express `bodyParser()` used within the server example seems to have been [deprecated](https://github.com/expressjs/body-parser/commit/b7420f8dc5c8b17a277c9e50d72bbaf3086a3900) within Express version 4 (released after 2014-06-19). What version of Express are you currently running? Can you verify that Express 3.x is still failing?

**Comment by quisse** [comment]
I'm using 4.13.1, so no I think 3.x works. but in "s3handler.js" it says express 3.3.5+. When i saw express.bodyParser() was deprecated i thought the body-parser would solve it. Maybe it's less confusing when in comments it says it is'nt compatible with 4.x. But, it can be fixed by using a formdata parser (like (formidable)[https://www.npmjs.com/package/formidable]

**Comment by dbeg** [comment]
When the Node.js server demo was created, I'm assuming `bodyParser()` (and Express 3.x, for that matter) had not yet been deprecated. Since you're using Express 4.x, I would not necessarily trust this code example.

Instead of using a differed parser, you might be able to simply [tweak your Express configuration](http://stackoverflow.com/a/24330353/5573660). If this is the case, perhaps you could fork this repo and create a pull request with a proper fix.
